### PR TITLE
Tech Debt: Add migrations

### PR DESCRIPTION
**Pull request by laveur**
When I initially started this project I had (incorrectly) assumed that Django migrations where intrinsically tied to the Database you were using. All these years later, I have learned that they are not.

Our Production server uses MySQL because our Website (Ran with Ghost CMS), and our Reg Software (ConventionMaster) only work with MySQL.

I personally prefer Postgres and use that on my local Mac for development.

This commit add's the current migrations from our production server, plus whatever was required to bring master (I need to change this to main) inline with it.

Sadly for anyone running a development version you will need to wipe out the database and start over :(

### CODE REVIEW

**Comment by laveur** [comment]
As a note: after these changes are made, you will probably need to make the function [`get_current_event`](https://github.com/pacanthro/paw_apply/blob/master/core/models.py#L4-L5) return `None` to make the migrations work. After making the migrations and getting the database seeded you can restore the original code.

**Review by deltaphor — APPROVED** [review]
Yup, can confirm I needed these migrations and patching `get_current_event` to get the site running.

**Comment by deltaphor** [comment]
FWIW it seems I also needed to manually create two `Table` objects with keys `FULL` and `DOUB` for a few pages.

**Comment by laveur** [comment]
@deltaphor Yeah I need to do some bootstrap when setting up a new system.

**Pull request merged**
